CREATE TABLE USUARIOS_2(

USUARIO_ID SERIAL PRIMARY KEY,
USUARIO_NOME VARCHAR(100) NOT NULL,
USUARIO_EMAIL VARCHAR(50) NOT NULL,
USUARIO_SENHA VARCHAR(20) NOT NULL,

USUARIO_PERFIL_ID INTEGER NOT NULL,
CONSTRAINT FK_USUARIOS FOREIGN KEY (USUARIO_PERFIL_ID) REFERENCES USUARIO_PERFIL(USUARIO_PERFIL_ID) 

)

SELECT * FROM USUARIOS_2

CREATE TABLE USUARIO_PERFIL(

USUARIO_PERFIL_ID INTEGER PRIMARY KEY,
USUARIO_PERFIL_DESC VARCHAR(50) NOT NULL

)

INSERT INTO usuario_perfil VALUES(2, 'FORNECEDOR')

SELECT * FROM USUARIO_PERFIL


DROP TABLE USUARIOS